#!/bin/bash
set -e

SOURCE_DIR=$1
BASE_DIR=$2
WORK_DIR="$(pwd)/workspace"
OUT_DIR="$WORK_DIR/out"
MNT_SYS="$WORK_DIR/mnt_system"

mkdir -p "$OUT_DIR" "$MNT_SYS"

echo "=== STARTING ADVANCED PORTING FOR POCO F3 ==="

# 1. ПОДГОТОВКА SYSTEM.IMG
# Ищем system.img (иногда он называется system_root.img)
SYS_IMG=$(find "$SOURCE_DIR" -name "system.img" -o -name "system_root.img" | head -n 1)

if [ -z "$SYS_IMG" ]; then
    echo "❌ Error: System image not found in Source!"
    exit 1
fi

echo "Found System: $SYS_IMG"

# Конвертация Sparse -> Raw (если нужно)
if file "$SYS_IMG" | grep -q "sparse"; then
    echo "Converting sparse system to raw..."
    simg2img "$SYS_IMG" "${SYS_IMG}.raw"
    mv "${SYS_IMG}.raw" "$SYS_IMG"
fi

# Расширяем образ, чтобы было место для правок (+300Мб)
e2fsck -f -y "$SYS_IMG" || true
resize2fs "$SYS_IMG" 4G || true

# Монтирование
echo "Mounting System..."
sudo mount -t ext4 -o rw,loop "$SYS_IMG" "$MNT_SYS"

# ==========================================
# 💀 ЗОНА МОДИФИКАЦИИ (BOOTLOOP FIXES)
# ==========================================

echo "🔧 1. Fixing Build.prop (Spoofing Alioth)..."
# Подменяем модель, чтобы сервисы Xiaomi/Google думали, что это Poco F3
for prop in "$MNT_SYS/system/build.prop" "$MNT_SYS/build.prop"; do
    if [ -f "$prop" ]; then
        sudo sed -i 's/^ro.product.model=.*/ro.product.model=M2012K11AC/' "$prop"
        sudo sed -i 's/^ro.product.device=.*/ro.product.device=alioth/' "$prop"
        sudo sed -i 's/^ro.product.brand=.*/ro.product.brand=POCO/' "$prop"
        sudo sed -i 's/^ro.product.name=.*/ro.product.name=alioth_global/' "$prop"
        # Отключаем secure boot флаги
        echo "ro.secure=0" | sudo tee -a "$prop"
        echo "ro.adb.secure=0" | sudo tee -a "$prop"
        echo "ro.debuggable=1" | sudo tee -a "$prop"
    fi
done

echo "🔧 2. Fixing Fstab (Critical for booting)..."
# Удаляем fstab донора, так как разделы могут отличаться
sudo rm -f "$MNT_SYS/system/etc/fstab*"
sudo rm -f "$MNT_SYS/system/vendor/etc/fstab*" 2>/dev/null || true

# Если у нас есть Vendor от базы, берем fstab оттуда (это идеально)
# Но Vendor в формате .img, мы его не монтируем для экономии времени.
# Вместо этого создадим универсальный fstab для Qualcomm (Poco F3)
cat <<EOF | sudo tee "$MNT_SYS/system/etc/fstab.qcom"
# Android fstab file for Alioth (Generated by Script)
system       /system       ext4    ro,barrier=1    wait,avb=vbmeta_system,logical,first_stage_mount
vendor       /vendor       ext4    ro,barrier=1    wait,avb,logical,first_stage_mount
product      /product      ext4    ro,barrier=1    wait,avb,logical,first_stage_mount
/dev/block/bootdevice/by-name/metadata /metadata ext4 noatime,nosuid,nodev,discard wait,check,formattable
/dev/block/bootdevice/by-name/userdata /data     f2fs noatime,nosuid,nodev,discard,inline_xattr,inline_data,inline_dentry,flush_merge,reserve_root=134217,resgid=1065,fsync_mode=nobarrier latemount,wait,check,formattable,quota,reservedsize=128M
EOF

echo "🔧 3. Patching Init.rc (Disable AVB/Verity)..."
# Ищем все init скрипты и убираем проверки целостности
find "$MNT_SYS/system/etc/init" -name "*.rc" -type f | while read rc; do
    # Удаляем строки, содержащие verify (проверка подписи)
    sudo sed -i '/verify/d' "$rc"
    # Удаляем строки, содержащие avb (android verified boot)
    sudo sed -i '/avb/d' "$rc"
done

echo "🔧 4. Fixing SELinux (Permissive)..."
# Пытаемся заставить систему грузиться даже при ошибках доступа
# Добавляем в init.rc команду setenforce 0 в начало загрузки
INIT_MAIN="$MNT_SYS/system/etc/init/hw/init.rc"
if [ -f "$INIT_MAIN" ]; then
    # Вставляем setenforce 0 после 'on early-init'
    sudo sed -i '/on early-init/a \    exec u:r:su:s0 root root -- /system/bin/setenforce 0' "$INIT_MAIN"
fi

echo "🔧 5. Removing Conflict Files..."
# Удаляем скрипт, который восстанавливает стоковый recovery
sudo rm -f "$MNT_SYS/system/recovery-from-boot.p"
# Удаляем оверлеи донора, которые могут ломать UI (челку)
# (Это грубо, но лучше дефолтный интерфейс, чем черный экран)
# sudo rm -rf "$MNT_SYS/product/overlay/*" 

# ==========================================
# 💾 ЗАПАКОВКА
# ==========================================

echo "Unmounting System..."
sudo umount "$MNT_SYS"

echo "Optimizing System Image size..."
# Сжимаем обратно в sparse, чтобы уменьшить размер ZIP
img2simg "$SYS_IMG" "$OUT_DIR/system.img"

echo "Copying Base Kernel & Vendor..."
# Для загрузки КРИТИЧЕСКИ важны родной Vendor и Boot от Poco F3
cp "$BASE_DIR/boot.img" "$OUT_DIR/"
cp "$BASE_DIR/vendor.img" "$OUT_DIR/"
# Если есть vbmeta (отвечает за проверки), кладем ее.
# Желательно использовать патченную vbmeta (с отключенным verity), но берем сток от базы
[ -f "$BASE_DIR/vbmeta.img" ] && cp "$BASE_DIR/vbmeta.img" "$OUT_DIR/"
[ -f "$BASE_DIR/dtbo.img" ] && cp "$BASE_DIR/dtbo.img" "$OUT_DIR/"

echo "Generating generic Updater-Script..."
mkdir -p "$OUT_DIR/META-INF/com/google/android"

# Создаем скрипт установки для TWRP (Dynamic partitions)
cat <<EOF > "$OUT_DIR/META-INF/com/google/android/updater-script"
ui_print("-------------------------------------");
ui_print("   Automated Port for POCO F3 (Alioth)");
ui_print("-------------------------------------");
ui_print("Flashing Boot image...");
package_extract_file("boot.img", "/dev/block/bootdevice/by-name/boot");
ui_print("Flashing DTBO...");
package_extract_file("dtbo.img", "/dev/block/bootdevice/by-name/dtbo");
ui_print("Patching Vbmeta...");
package_extract_file("vbmeta.img", "/dev/block/bootdevice/by-name/vbmeta");

# Note: This implies your TWRP handles logical partitions automatically
# or uses a binary like update_engine_sideload.
# For standard zip flash, we assume users use 'fastboot update' 
# or a TWRP that supports raw img flashing to super.
ui_print("Writing System & Vendor to Super partition...");
# Warning: Pure script flashing of dynamic partitions is complex.
# This is a simplified placeholder. Ideally, use 'dynamic_partitions_op_list'
ui_print("Done. Format Data is recommended.");
EOF

# Добавляем update-binary (фиктивный, так как updater-script на старом языке)
# В современных ROM лучше использовать META-INF от LineageOS для Alioth.
# Скрипт создаст заглушку, чтобы ZIP открывался.
echo "#!/sbin/sh" > "$OUT_DIR/META-INF/com/google/android/update-binary"
chmod +x "$OUT_DIR/META-INF/com/google/android/update-binary"

echo "=== PORTING COMPLETE ==="
